# Generated by Django 4.1.7 on 2023-03-24 05:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Inflearn_lecture", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mytext",
            name="board_text",
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
