# Generated by Django 4.1.7 on 2023-03-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Inflearn_lecture", "0003_alter_mytext_board_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="mytext",
            name="category",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
