# Generated by Django 4.1.7 on 2023-03-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Inflearn_lecture", "0004_mytext_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mytext",
            name="img_url",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
